### ISSUE TITLE
August 15 Hacknight – Kei Williams #BlackLivesMatter

### ISSUE THREAD

**Issue by rapicastillo** [ProgressiveHackNight/admin#19]
# About

<img src="https://user-images.githubusercontent.com/399692/29029025-3b2fbfa4-7b54-11e7-93b8-3d70aac370bf.png" width="250px" styled="margin-right: 10px; float: left;" /> 
Kei Williams is a queer transmasculine identified community organizer with #BlackLivesMatter, NYC Chapter. A self-taught visual artist & graphic designer, they assist small businesses and nonprofit organizations with communications, marketing, and social media. Kei centers their work on those most marginalized in society: transgender persons and those who suffer from mental illness. Kei will talk about their story and where they are now, their work with #BlackLivesMatter, and how technologists can support and amplify the movement for black lives.

# Host/s

The hosts for this event is @laveshaparker and @ibrand 

# Todo's

## Speaker specific

- [x] Reach out to Speaker, have them agreed to speak
- [x] Send speaker guidelines and other samples of events
- [x] Get sign-off on "About the speaker" / event language to be used
- [x] Have a phonecall with speaker to orient them about the event
- [x] Request the items @julianrad has asked from the speaker:

```
• Correct Spelling of NAME
• Title for Lower Thirds
• Company or Organization Affilitation
• Facebook and Twitter handles
• Personal website or Organization website
• Three of four facts or surprising thoughts that relate to the talk they're going to give that we can use to help promote on social media. Something along the lines of “XXX happened and now we’re doing XXX and we’re going to talk more about that at PHN” sort of thing.
• If they have a deck, I’d love to have it the night before. 
• Make sure that they're cool with being videotaped/livestreamed?
```

## Breakout Groups

- [x] Reachout to breakout groups
- [x] Have clarity on locations of breakout groups in the space
- [x] Send email to breakout group leads asking if they're going to participate on the hacknight

## Event specific actions
_Related to the location and event itself_

- [ ] Reachout to potential Pizza Sponsor
- [ ] Reachout to potential Drink Sponsor
- [x] Venue clear for use in ThoughtWorks? Where? (Main conference / Back)
- [x] Clarity on what are the spaces available
- [x] Agenda already set
- [x] Announcements list set?

## Outreach Actions

- [x] progressivehacknight page already setup
- [x] Our Meetup.com page set up?
- [x] Sent email of thanks to participants? Monday/Tuesday
- [x] Sent email of tips/best practices to participants? Wednesday/Thursday
- [x] Sent email of invite to participants – Friday / Monday
- [x] Reachout to amplification partners / people who have expressed interest in amplifying our event.
- [x] Reach out to Code for Good
- [x] Reach out to Civic Hall

**Comment by rapicastillo** [comment]
Agenda: https://docs.google.com/document/d/1JG8Vm9P_u_giwF4A7rQ6vDmP-hYSzvEtKS7AA2uKp0Q/edit#

Meetup.com: https://www.meetup.com/Progressive-Hack-Night/events/241861001/
